### ISSUE TITLE
Proposal: Make data parameter optional

### ISSUE THREAD

**Issue by oomathias** [afitiskin/redux-saga-actions#1]
Since you removed form from the name, I'm guessing you want to be able to use this to dispatch any async actions.

Make data parameter optional, we can call:

```js
componentWillMount() {
  fetchData(this.props.dispatch)
}
```

instead of 

```js
componentWillMount() {
  fetchData(undefined, this.props.dispatch)
}
```

**Comment by afitiskin** [comment]
Sometimes you really need to have payload for dispatched actions. For example you would like to load data without UI changes, so you will use something like `fetchData({ notify: false }, this.props.dispatch)`.

I could recommend you to use `bindSagaActions` helper (similar to [`bindActionCreators`](http://redux.js.org/docs/api/bindActionCreators.html) helper from `redux`) to simplify usage of generated actions. See the example below:

```javascript
// utils/bindSagaActions.js

function bindSagaAction(sagaAction, dispatch) {
  return (payload) => sagaAction(payload, dispatch);
}

export default function bindSagaActions(sagaActions, dispatch) {
  if (typeof sagaActions === 'function') {
    return bindSagaAction(sagaActions, dispatch);
  }

  if (typeof sagaActions !== 'object' || sagaActions === null) {
    throw new Error(
      `bindSagaActions expected an object or a function, instead received ${sagaActions === null ? 'null' : typeof sagaActions}. Did you write "import sagaActions from" instead of "import * as sagaActions from"?`
    );
  }

  const keys = Object.keys(sagaActions);
  const boundSagaActions = {};
  for (let i = 0; i < keys.length; i++) {
    const key = keys[i];
    const sagaAction = sagaActions[key];
    if (typeof sagaAction === 'function') {
      boundSagaActions[key] = bindSagaAction(sagaAction, dispatch);
    }
  }
  return boundSagaActions;
}
```

```javascript
// components/MySmartComponent.js

import bindSagaActions from '../utils/bindSagaActions';
import { connect } from 'react-redux';

import { fetchData } from './actions';

class MySmartComponent {
  static propTypes = {
    fetchData: PropTypes.func.isRequired, // require fetchData function
  };
  
  static mapDispatchToProps(dispatch) {
    return bindSagaActions({ fetchData }, dispatch); // bind fetchData to dispatch, and pass it to component property
  }

  static mapStateToProps(state) {
    return {}; // select necessary data from state here
  }
  
  componentWillMount() {
    this.props.fetchData(); // or this.props.fetchData(payload) if necessary
  }

  render() {
    return (...); // component contents here
  }
}

// should export connected component as a default
export default connect(MySmartComponent.mapStateToProps, MySmartComponent.mapDispatchToProps)(MySmartComponent);
```

**Comment by afitiskin** [comment]
There are also easier way to bind `fetchData`, cause `connect` internally uses `bindActionCreators`.

**Comment by afitiskin** [comment]
Sorry, I closed issue accidentally. 

When I forked `redux-form-saga` to make this package, I kept in mind idea to rename these kind of actions to `routines`. So the API can be something like:
`actionsWatcherSaga` -> `routineWatcherSaga`
`createAction` -> `createRouting`

Also I prefer to add `bindSagaActions` from example below to the package, but rename it to `bindRoutineCreators` (similar to `bindActionCreators`).

What do you think?

**Comment by oomathias** [comment]
Wow, thanks!

Does the job perfectly, I also wanted to get rid of that dispatch in my component.

Looks like this now:

```js
connect(
  null,
  (dispatch) => bindSagaActions({ fetchData }, dispatch)
)(MyComponent)
```

```js
componentWillMount() {
  this.props.fetchData()
}
```

> `createAction` -> `createRouting`

`createRoutine` ?

Yes, I think it would be a great addition to this package

**Comment by afitiskin** [comment]
> createRoutine ?

Of course! Stupid misprint :)

**Comment by afitiskin** [comment]
> Yes, I think it would be a great addition to this package

The problem is the name of the package. I would like to rename it to `redux-saga-routines`, but I don't know how to make it in most right way... Any Ideas?

**Comment by oomathias** [comment]
On GitHub side, I think it's pretty easy since you will have a redirection to the new name.
On npm side, you can deprecate this one and add a warning with the new name.

```
npm deprecate %ProjectName%@"<=put-latest-version-here" "WARNING: This project has been renamed to %NewProjectName%. Install using %ProjectName% instead."
```
